### ISSUE TITLE
Content Decoding Failure

### ISSUE THREAD

**Issue by kevdel** [wiedehopf/timelapse1090#1]
Running the latest github version I get the following error within Chrome when processing the chunk_[n].gz files

Failed to load resource: net::ERR_CONTENT_DECODING_FAILED 

checked on firefox and the same issue
weird thing is when i do a curl to the gz ip file and use gunzip I get valid JSON

server is running on Rasbian

**Comment by wiedehopf** [comment]
This can happen if  this line
```
server.modules += ( "mod_setenv" )
```
is present twice in the lighttpd config.

Re-running the install should take care of that, it automatically looks for duplicates of that line.
(It's set by both dump1090-fa and skyview978)

If you have it set in your main lighttpd config, you can remove that line from the dump1090-fa lighttpd config file as well.

Even if the above is not the case, the problem sounds like a header problem, so check the header:

```
wget --server-response http://localhost/timelapse/data/chunk_0.gz -O /dev/null
```

For me it looks like this:
```
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Content-Type: application/gzip
  Content-Type: application/json
  Accept-Ranges: bytes
  ETag: "2859094101"
  Last-Modified: Wed, 17 Jul 2019 16:38:37 GMT
  Access-Control-Allow-Origin: *
  Cache-Control: must-revalidate
  Content-Encoding: gzip
  Content-Length: 2474853
  Date: Thu, 18 Jul 2019 06:57:14 GMT
  Server: lighttpd/1.4.53
Length: 2474853 (2.4M) [application/gzip]

```

**Comment by kevdel** [comment]
Thanks for getting back

1) Checked the lighttpd.conf file and only 1 reference to the mod_setenv
```
GNU nano 2.2.6 File: /etc/lighttpd/lighttpd.conf 
server.modules = (
"mod_access",
"mod_alias",
"mod_compress",
"mod_redirect",
"mod_auth",
"mod_setenv",
"mod_status",
"mod_accesslog",
)
```

2) Headers look different than yours (notably the size difference for the gz file and the duplication of header entries)

```
pi@777-300ER:~ $ wget --server-response http://localhost/timelapse/data/chunk_0.gz
converted 'http://localhost/timelapse/data/chunk_0.gz' (ANSI_X3.4-1968) -> 'http://localhost/timelapse/data/chunk_0.gz' (UTF-8)
--2019-07-18 11:04:15-- http://localhost/timelapse/data/chunk_0.gz
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response...
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
Cache-Control: must-revalidate
Cache-Control: must-revalidate
Content-Encoding: gzip
Content-Encoding: gzip
Content-Type: application/json
Content-Type: application/json
Accept-Ranges: bytes
ETag: "2155019625"
Last-Modified: Wed, 17 Jul 2019 22:39:00 GMT
Content-Length: 698583
Date: Thu, 18 Jul 2019 16:04:15 GMT
Server: lighttpd/1.4.35
Length: 698583 (682K) [application/json]
Saving to: 'chunk_0.gz.1
```

**Comment by wiedehopf** [comment]
`Checked the lighttpd.conf file and only 1 reference to the mod_setenv`

Well remove it there.
It is defined as well here: /etc/lighttpd/conf-enabled/89-dump1090-fa.conf

**Comment by wiedehopf** [comment]
Or you can remove it from 89-dump1090-fa.conf
It really doesn't matter as long as it's only defined once.

Defined twice it will produce double header entries.
Lighttpd truely is a awful piece of programming it seems.

**Comment by kevdel** [comment]
yep, that fixed it..

thanks again!
