### ISSUE TITLE
Suggestion: Save NEXRAD Weather

### ISSUE THREAD

**Issue by kevdel** [wiedehopf/timelapse1090#2]
Would it be feasible to save the weather layer with the aircraft position data over time and replay both?

**Comment by wiedehopf** [comment]
I don't have NEXRAD here.
Would sure be nice, but i don't even know how NEXRAD is handled by dump1090-fa.

So it might be possible, but i'm not inclined to investigate further.

**Comment by wiedehopf** [comment]
Implement it yourself, make a pull request ;)
