### ISSUE TITLE
More history than 24hrs possible?

### ISSUE THREAD

**Issue by Hammer73** [wiedehopf/timelapse1090#3]
Apologies if this is the wrong place / way to ask a question. Still new to ADSB/Dump1090. 
Is it possible in the time-lapse to go back more than 24 hours? While I followed the instructions to set the parameter (for me 72 or more hours would be great) and restarted the app I don't seem to be able to 'browse' back passed 'midnight'. Probably I'm the 'issue' here but can you point me in the right direction?  tnx! ps Keep up this great work!

**Comment by wiedehopf** [comment]
you waited more than 24h since you made the switch?

maybe your RPi reboots at midnight? the history is only kept in memory.

**Comment by Hammer73** [comment]
Ah... That's probably it! Also explains why I din't see any disk usage increase. (as said... still figuring these apps out. Appreciate the work and quick response!

**Comment by utack** [comment]
Do you know any very rough memory requirements for a normal area with something like 300 aircraft a day tracked over 100nm?  
are we talking 10mb or multiple hundreds?

**Comment by wiedehopf** [comment]
```
 du -sh /run/timelapse1090 
18M	/run/timelapse1090
```

![image](https://user-images.githubusercontent.com/6976172/85632102-f588c980-b676-11ea-8890-98668b286dd6.png)

**Comment by wiedehopf** [comment]
Oh .... that's double the normal usage because i decreased the interval from 10 to 5 seconds.

**Comment by utack** [comment]
Thank you :)  
So basically the important factor is how much the client browser breaks, not how much you save
