### ISSUE TITLE
[Feature Request] Store Data for Long Term Logging 

### ISSUE THREAD

**Issue by CactusProjects** [wiedehopf/timelapse1090#4]
The tar1090 family of packages are amazing, would it be possible to store the data locally (permanently) so any time period could be queried?

**Comment by wiedehopf** [comment]
I'm don't want to support such a feature, it will draw many problems i don't to deal with.

My readsb dev branch together with nginx and tar1090 allows to save traces.
Those only contain altitude and positions.

See the history tab when selecting an aircraft on adsbexchange: https://tar1090.adsbexchange.com/

But it's not completely foolproof to configure and for the foreseeable future only holds altitude/positions information.

I'd strongly suggest setting up a secondary readsb service that's net-only and get's it's data via network 

The relevant command line options:

```
--net-only --net-connector localhost,30005,beast_in --write-json-globe-index --write-globe-history /var/globe_history
```

The directory needs to be created and the ownership given to the user the service runs as.
tar1090 needs to be configured to use the data from the appropriate /run directory (see multiple instances tar1090).
If nginx is installed, tar1090 will advise which conifguration file to include.

Now you'll have to figure the rest out yourself, as i said i'm not prepared to support this for everyone.
It's only for people who can read all the relevant help pages and --help outputs from readsb.

**Comment by CactusProjects** [comment]
Okay I appreciate the reply, thanks for all the work on the existing packages.
