### ISSUE TITLE
Remove RM commands from startup

### ISSUE THREAD

**Issue by trenchcoatjedi** [wiedehopf/timelapse1090#9]
What would be the effect of removing the rm commands during startup? I would like to create timelapse1090 data that persists indefinitely and survives reboot. Could this be added?

**Comment by wiedehopf** [comment]
I don't have any interest in this project anymore.

Have a look at readsb / tar1090 replay.

Modify the scripts for this yourself if you care.
Be aware that the scripts here are meant to use tmpfs they write much more data than an application that would write to non volatile storage.
